live_config_reload = true

# catppuccin-mocha.toml
# rose-pine.toml


import = [
    "~/.config/alacritty/themes/rose-pine.toml"
]

[font]
size = 9

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "SemiBold Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "SemiBold"

[env]
TERM = "xterm-256color"
